---
- hosts: db
  vars:
    db_password: password
  tasks:
    - name:   Copies Module ; on local host on to remote host
      become: yes
      copy: src=db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644
    
    - name: Install MariaDB  
      become: yes
      yum: name=MariaDB-server,MariaDB-client update_cache=yes state=present

    - name: On Boot : Starts MariaDB
      become: yes
      service: name=mariadb state=started enabled=yes

    - name: Template that Injects Variable Data into MariaDB
      template: src=db/mariadb_answers.txt dest=/tmp/mariadb_answers.txt mode=0644

    - name: Reads MariaDB.txt File ; Redirected to mysql_secure_installation
      become: yes
      shell: /usr/bin/mysql_secure_installation </tmp/mariadb_answers.txt

    - name: Unzips Package ; From Remote to Host Machine
      unarchive: src=db/db.tgz dest=~/ mode=0755

    - name: Runs Database Command ; Injects DB_PW on LocalHost
      command: ./make_databases.sh {{ db_password }} localhost chdir=~/db
      ignore_errors: True
